### ISSUE TITLE
bug in alcuni twig, chiamata funzione monthEn2It con parametro errato

### ISSUE THREAD

**Issue by rdemichele** [italia/design-comuni-drupal-theme#13]
In alcuni casi la funzione twig `monthEn2It` viene chiamata con primo parametro `date("F")` (`January`) ma per come è attualmente scritta dovrebbe essere sempre chiamata con primo parametro in formato `date("M")` (`Jan`).

### Esempio:
**File** \design-comuni-drupal-theme\comuni_theme\templates\paragraphs\paragraph--calendario.html.twig
**Riga 69** {% set currentMonth = "now"|**date("F")**|**monthEn2It**(false) %}

**File** \design-comuni-drupal-theme\src\TwigExtension\ComuniTwig.php
Si aspetta come indice `date("M")`

public function monthEn2It(`$englishName`, $short=true) {
    if ($short) {
        $months = array(
            '`Jan`' =>  'Gen',
            ...
        );
    } else {
        $months = array(
            '`Jan`' =>  'Gennaio',
            ...
        );
    }
    return $months[`$englishName`];
}

**Comment by astagi** [comment]
@rdemichele grazie della segnalazione! Corretta [qua](https://github.com/italia/design-comuni-drupal-theme/pull/14). Entro la fine della giornata di domani rilasceremo una nuova versione del tema.
