### ISSUE TITLE
Errore su vista Bandi

### ISSUE THREAD

**Issue by whiteseraph83** [italia/design-comuni-drupal-theme#16]
Buongiorno,
abbiamo rilevato un errore nella vista Bandi.
Dallo screenshot, cliccando sul filtro evidenziato non appariva nessuna selezione (Forse durante lo sviluppo un termine è stato eliminato)
Immaginiamo che i termini da selezionare in questo contesto siano quelli collegati ai bandi.

![immagine](https://user-images.githubusercontent.com/29896419/202415765-c2b132b2-79b6-4efb-b310-c85f8cdd16d5.png)

Le pagine che richiamano questa vista sono quelle relative alla "Categoria di servizio" (https://italia.github.io/design-comuni-pagine-statiche/sito/template-servizi-servizio.html)

Grazie,
e buon lavoro

**Comment by zetareticoli** [comment]
Ciao @whiteseraph83, non siamo riusciti a replicare il bug. 

Posso chiederti se avete importate tutti i termini della tassonomia in modo corretto (utilizzando quelli necessari) o sono state fatte modifiche?

**Comment by smaraschin** [comment]
Ciao @zetareticoli, no no abbiamo creato un istanza pulita proprio per fare questi test.

Allora se vai nella vista Bandi all'url "/admin/structure/views/view/bandi", già dall'anteprima del filtro del campo tassonomico "Tipo Documento albo pretorio" (che si riferisce al vocabolario "Documenti albo pretorio") puoi notare che verrebbe selezionato un termine che inizia con "Denunci..."  però cliccandoci il termine non è proprio presente, infati la selezione è vuota.

Abbiamo scaricato l'ultima versione di Taxonomy.tar.gz e per il vocabolario "Documenti albo pretorio" non esiste alcun termine che inizia con "Denunci..."

![immagine](https://user-images.githubusercontent.com/95076111/205253976-b8be1df8-1334-4c95-967c-b5a29f7dc788.png)

Nota:
Non so se aiuta a risolvere... però abbiamo notato che nel vocabolario "Eventi della vita delle persone" invece è presente il termine "Denuncia crimini"

**Comment by rdemichele** [comment]
Ciao,
abbiamo capito il problema: quando vengono importati i vocabolari, i termini non hanno l'id che la vista si aspetta nei filtri proposti.

Esempio: **views.views.bandi.yml** si aspetta che gli "Bando, Bando di concorso, Bando di contributi e vantaggi economici, Bando di gara" abbiano gli id 345, 346. 348. 347 ma nella nostra istanza questi termini appartengono a vocabolari diversi (gli id dei nostri termini corretti sono: 111, 112, 113, 114).

Ci sembra che solo questa vista abbia dei filtri specifici sui termini.

Non credo si possa risolvere via codice, eventualmente potrebbe essere aggiunto un commento sulla guida per controllare ed eventualmente assegnare manualmente i termini sulla vista. Oppure bisogna trovare o configurare un importatore che mantenga gli stessi id o che vada a correggere la vista in fase di importazione.
