### ISSUE TITLE
Contenuto Notizia

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#18]
Buongiorno,
abbiamo notato che il contenuto Notizia non mostra nella pagina di dettaglio i campi "Dataset" e "Documenti" se vengono inseriti.

Inoltre il campo Allegati ha come label "Documenti"

Grazie
buon lavoro

**Comment by astagi** [comment]
Buonasera @White-Seraph puoi allegare alcuni screenshot relativi al problema? Grazie!

**Comment by rdemichele** [comment]
Buonasera, allego screenshot
- Campo Allegati viene visualizzato con titolo Documenti;
- Campi Dataset e Documenti non vengono mostrati (attualmente non sono presenti nei template html);
![image](https://user-images.githubusercontent.com/103657056/202465376-55b8467c-a100-41ae-8c26-fe17c0b96c2c.png)

**Comment by astagi** [comment]
Perfetto, grazie mille @White-Seraph gentilissimo!
