### ISSUE TITLE
Errore su pagina "Vivere il comune"

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#19]
Buongiorno,
abbiamo notato che se nel paragraph "Container contenuti in evidenza" dedicato ai luoghi viene selezionato un luogo che non ha compilato il campo "Tipo di luogo" (che non è obbligatorio) la pagina va in crash.
Riga 124 del file twig:
\templates\node\node--luogo--teaser-in-evidenza.html.twig
`href="{{ path('entity.taxonomy_term.canonical', { 'taxonomy_term': node.field_tipo_di_luogo.entity.tid.value }) }}"`

Grazie
Buon lavoro

**Comment by astagi** [comment]
@White-Seraph grazie delle segnalazioni! Procedo a riportarle al team di sviluppo.
