### ISSUE TITLE
Paragraph Container Top Cards

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#20]
Buongiorno, abbiamo notato che se viene aggiunto un paragraph di tipo "Container Top Cards", questo non ha un wrapper con la classe bootstrap "container", quindi si estenderà per tutta la larghezza dello schermo.

Ecco lo screenshot di esempio:
![immagine](https://user-images.githubusercontent.com/95076111/202489925-9d52a64d-14e3-4c7c-85c0-272767626571.png)

Grazie ancora per il lavoro
saluti

**Comment by rdemichele** [comment]
Noi abbiamo aggiunto al twig templates\paragraphs\paragraph--homepage-top-cards.html.twig i seguenti contenitori:
```
	<div class="section section-muted pt-0 pb-1">
		<div class="container">

```

**Comment by astagi** [comment]
@rdemichele potete aprire una PR che aggiunge i contenitori? Almeno la rendiamo disponibile a tutti.

Grazie infinite 🙏

**Comment by zetareticoli** [comment]
@rdemichele come vi suggeriva @astagi , se create la PR aggiungiamo al tema, grazie

**Comment by zetareticoli** [comment]
@White-Seraph vuoi procedere tu con la modifica proposta da @rdemichele aprendo la PR?

**Comment by zetareticoli** [comment]
@smaraschin Aggiornamento in merito alla issue aperta:

Container top cards è pensato per essere inserito dentro a container calendario. Quindi le tre cards in cima all'Homepage devono essere poste all'interno del container Calendario. Se vengono messe direttamente in Homepage non hanno un container e quindi vengono mostrate senza gli stili (perché hanno degli stili condivisi).

**Comment by astagi** [comment]
@smaraschin @rdemichele da codice sembrerebbe corretto https://github.com/italia/design-comuni-drupal-theme/blame/ec3889b18ebfc629a435225aad14fd6661cd631d/comuni_theme/templates/paragraphs/paragraph--container-calendario.html.twig#L55

**Comment by smaraschin** [comment]
Ciao Andrea, era solo un suggerimento per migliorare l'usabilità del gestionale.
Attualmente infatti il paragraph chiamato `Container Calendario` contiene al suo interno un ulteriore paragraph chiamato `Top Cards` oltre al paragraph `Calendario` e quindi lato gestionale visto che `Container calendario` parte collassato non è intuitivo che bisogna aprirlo per trovare Top card per modificarlo.

Un suggerimento veloce per migliorare l'usabilità è di rinominare `Container calendario` in `Container calendario e Top Cards`

Ad ogni modo non è assolutamente una priorità
ciao
