### ISSUE TITLE
Content Type Luogo

### ISSUE THREAD

**Issue by SonOfV** [italia/design-comuni-drupal-theme#23]
Buongiorno,
abbiamo notato che il content type di tipo luogo non carica lo stile lato front-end.

Di seguito uno screenshot di esempio:
![image](https://user-images.githubusercontent.com/34920748/202672176-949aef09-1518-49f5-84ca-d0516c1b0533.png)

**Comment by zetareticoli** [comment]
Ciao @SonOfV,
grazie della segnalazione, è una problematica di cui siamo al corrente e presto il template del _content type_ Luogo sarà rilasciato sul repo [design-comuni-pagine-statiche](https://github.com/italia/design-comuni-pagine-statiche).

Sarà quindi possibile seguire quel template .html per implementarlo nel tema Drupal.

**Comment by astagi** [comment]
Ciao @SonOfV , non abbiamo ancora un piano di rilasci definito che preveda l'aggiunta dei templates per altri content-type. Nel frattempo, posso solo suggerirti di crearli in autonomia seguendo le indicazioni del [documento di Architettura dell'Informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=1529184526).

Nel caso decidessi di realizzarli, puoi mettere a riuso della community eventuali sviluppi aprendo una pull request :)
