### ISSUE TITLE
Layout sezione Amministrazione Trasparente

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#37]
Buongiorno,
avremmo bisogno di sapere se era già stato pensato il layout per la sezione in oggetto. Attualmente è assente anche nei template in html.
In caso contrario chiediamo indicazioni su come procedere.

Grazie

**Comment by zetareticoli** [comment]
Ciao @White-Seraph, 
ad oggi non ci sono indicazioni specifiche previste dal modello. Faremo un ulteriore verifica interna e vi facciamo sapere come regolarsi in linea generale.
