### ISSUE TITLE
Personalizzazione colori tema

### ISSUE THREAD

**Issue by savdev11** [italia/design-comuni-drupal-theme#42]
Buongiorno,
avrei la necessità di cambiare i colori del tema.
Ho notato che cambiando i colori delle variabili in "comuni_theme/node_modules/bootstrap-italia/src/scss/bootstrap-italia-comuni.scss" e poi ricompilando lanciando `npm run build` da "comuni_theme/node_modules/bootstrap-italia" (come da linee guida bootstrap italia) vengono cambiati solo alcuni colori.
Altri come, la classe .t-primary, sono contenuti nel file "comuni_theme/css/styles.css" e non ho trovato modo di cambiarli se non manualmente. 
C'è modo di rigenerare anche il file styles.css?

**Comment by astagi** [comment]
@savdev11 il file style.css viene preso direttamente dal repository Comuni pagine statiche (https://github.com/italia/design-comuni-pagine-statiche), occorre agire su quello per ricompilare uno style con i colori (ed eventuali personalizzazioni) voluti.

**Comment by astagi** [comment]
@savdev11 ci sono aggiornamenti su questa problematica?

**Comment by savdev11** [comment]
@astagi Si, sono riuscito a compilare il nuovo styles.css usando il repository Comuni pagine statiche, ma alcuni componenti rimangono del colore originale, come ad esempio i chip. Osservando il codice del repository ho notato che questo componente nello specifico ha il colore originale "hard-coded" ([src\components\partials\cmp-tag\cmp-tag.scss](https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/components/partials/cmp-tag/cmp-tag.scss)). Altri elementi che ho notato rimanere del colore originale sono nel menù mobile: il nome del comune e la scritta "seguici su" (Sempre con colori "hard-coded" in questo [file](https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/components/header/header.scss) .

**Comment by savdev11** [comment]
@astagi Salve, ci sono sviluppi a riguardo? Apro la stessa issue sul [repository Comuni pagine statiche ](https://github.com/italia/design-comuni-pagine-statiche)?

**Comment by astagi** [comment]
@savdev11 abbiamo aperto la PR di aggiornamento di Bootstrap Italia (2.3.4) dove dovrebbe risolversi il problema che hai riscontrato. Se hai modo di mergiare quella PR e darci un feedback sarebbe fantastico!

**Comment by astagi** [comment]
PR mergiata, procederemo al rilascio del tema. Per ora chiudo la issue se si ripresenta apriamone una nuova. Grazie ancora!
