### ISSUE TITLE
Content Type Persona pubblica

### ISSUE THREAD

**Issue by bit-mmontuschi** [italia/design-comuni-drupal-theme#44]
Buongiorno,
abbiamo notato che il content type di tipo persona non carica lo stile lato front-end.

Di seguito uno screenshot di esempio:

![persona](https://user-images.githubusercontent.com/122972923/213135880-9eec08cf-fbcf-4285-a627-6ef360012771.jpg)

Grazie per l'ottimo lavoro

**Comment by astagi** [comment]
Ciao @bit-mmontuschi, non abbiamo ancora un piano di rilasci definito che preveda l'aggiunta dei templates per altri content-type. Nel frattempo, posso solo suggerirti di crearli in autonomia seguendo le indicazioni del [documento di Architettura dell'Informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=1529184526).

Nel caso decidessi di realizzarli, puoi mettere a riuso della community eventuali sviluppi aprendo una pull request :)

**Comment by zetareticoli** [comment]
Ciao @bit-mmontuschi, in aggiunta a quanto segnalato da @astagi puoi seguire il [layout](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/%5BComuni%5D-Modello-sito-e-servizi?node-id=24059%3A198882&t=81BSXw5ukqwPKpsS-1) rilasciato settimana scorsa.

È stato realizzato utilizzando stili e classi disponibili con Bootstrap Italia, più elementi del modello Comuni già presenti in altri template.

Non abbiamo (ancora) previsione di quando riusciremo a pubblicare anche il template statico.

**Comment by bit-mmontuschi** [comment]
Grazie
buon lavoro
