### ISSUE TITLE
Titolo e descrizione pagina non editabili in modifica

### ISSUE THREAD

**Issue by bit-mmontuschi** [italia/design-comuni-drupal-theme#45]
Il paragraph type Titolo e descrizione nel contenuto Pagina
non risultano più editabili in fase di Modifica.
E' un comportamento  atteso e previsto?

Il Drupal in uso è la versione 9.5.1

![novita](https://user-images.githubusercontent.com/122972923/213221084-25dab2fe-a931-4734-83e3-281a208bff5b.jpg)

**Comment by astagi** [comment]
Buongiorno @bit-mmontuschi ci sono novità dopo le ultime release in merito a questa issue?
