### ISSUE TITLE
Tassonomia Amministrazione vs Tipo Unità organizzativa

### ISSUE THREAD

**Issue by bit-mmontuschi** [italia/design-comuni-drupal-theme#53]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il sito di riferimento del Comune di Cagliari sembra ignorare la tassonomia Tipo Unità organizzativa per ordinare la sezione Amministrazione, prediligendo invece il vocabolario Amministrazione, presente tra l'altro tra i vocabolari del tema ma assente nella documentazione della Architettura della informazione. 
E' corretto prediligere quindi quest'ultima tassonomia preferendola a Tipo Unità organizzativa? 

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.0.0

**Comment by zetareticoli** [comment]
Ciao @bit-mmontuschi , il sito del Comune di Cagliari adotta la versione precedente del modello, quindi il mio suggerimento è di basarti esclusivamente sul nuovo documento di Architettura dell'informazione.
