### ISSUE TITLE
ParseError: syntax error durante l'installazione

### ISSUE THREAD

**Issue by giannigiusti** [italia/design-comuni-drupal-theme#56]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Durante l'installazione, il comando

drush cim --partial --source=modules/custom/design-comuni-drupal-theme/comuni_theme/config/sync -y

Termina in modo inaspettato col seguente errore...

ParseError: syntax error, unexpected &#039;|&#039;, expecting &#039;;&#039; or &#039;{&#039; in Composer\Autoload\includeFile() (line 106 of /var/www/html/civicadesign/web/modules/contrib/color_field/src/Plugin/Field/FieldFormatter/ColorFieldFormatterText.php).
 [warning] Drush command terminated abnormally.

PHP ver 8

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.4.0

**Comment by astagi** [comment]
@giannigiusti grazie della segnalazione. Hai lo stesso problema anche con la versione 1.5.0 del tema?

**Comment by giannigiusti** [comment]
Provato con la 1.5.0 ....stesso errore

#37 /var/www/html/civicadesign15/vendor/drush/drush/drush(4): require('/var/www/html/c...')
#38 {main}
ParseError: syntax error, unexpected &#039;|&#039;, expecting &#039;;&#039; or &#039;{&#039; in Composer\Autoload\includeFile() (line 106 of /var/www/html/civicadesign15/web/modules/contrib/color_field/src/Plugin/Field/FieldFormatter/ColorFieldFormatterText.php).
 [warning] Drush command terminated abnormally.

**Comment by astagi** [comment]
@giannigiusti prova a far girare tutto con la versione di PHP 8.1
