### ISSUE TITLE
Template node--servizio.html.twig link con testo errato

### ISSUE THREAD

**Issue by giannigiusti** [italia/design-comuni-drupal-theme#58]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Inserendo nel campo "Canale digitale" il link e il testo da mostrare, la visualizzazione del nodo mostra sempre "Richiedi iscrizione online" nel pulsante visualizzato. Andrebbe cambiato il template "node--servizio.html.twig" alla riga 423 dall'attuale: 
`<span class="">Richiedi iscrizione online</span>`
con questa modifica
`<span class="">{{ content.field_canale_digitale['#items'][0].title }}</span>`

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.5.0

**Comment by astagi** [comment]
Grazie @giannigiusti potresti aprire una PR per questo fix?
