### ISSUE TITLE
Fax mancante in tassonomia Tipi punto di contatto

### ISSUE THREAD

**Issue by rdemichele** [italia/design-comuni-drupal-theme#69]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel contenuto "PUNTO DI CONTATTO" abbiamo necessità di aggiungere "Fax" nella tassonomia "tipo punto di contatto", visto che alcuni uffici ancora li ricevono.
Vorremmo sapere se possiamo aggiungerlo oppure c'è qualche normativa che vieta l'utilizzo di ulteriori punti di contatto.

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @rdemichele , può essere aggiunto senza problemi
