### ISSUE TITLE
Enhance campo "Condizioni di servizio" in contenuto "Servizio"

### ISSUE THREAD

**Issue by rdemichele** [italia/design-comuni-drupal-theme#70]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Proposta

Si potrebbe prevedere un'alternativa al file allegato, che corrisponda ad un link.

### Motivazione e contesto

Attualmente il campo in oggetto accetta solo file allegati (txt rtf doc docx ppt pptx xls xlsx pdf odf...),
consideriamo questo campo come il riferimento alla "carta dei servizi", è corretto?

**Comment by MarinaRepetto** [comment]
In aggiunta, approfittando anche di un confronto su slack relativo a questo tema, chiediamo che il campo "condizioni di servizio" sia un campo facoltativo e non obbligatorio, in quanto laddove il Comune ne dispone potrà contenere il link alla carta dei servizi o alla scheda del procedimento amministrativo (che non sono presenti per tutti i servizi), in altri casi i temini del servizio potrebbero essere espressi direttamente nell'applicativo che ospita il servizio online o, per servizi più semplici, tutte le informazioni potrebbero già essere state espresse testualmente nei contenuti della scheda servizio. In ogni caso ci sembra importante dare una maggiore libertà nella compilazione di questo campo per evitare una ridondanza e duplicazione di informazioni.
