### ISSUE TITLE
contenuto Unità Organizzativa, campi Responsabile e "Persone che compongono la struttura" sembrano invertiti

### ISSUE THREAD

**Issue by rdemichele** [italia/design-comuni-drupal-theme#71]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Come da oggetto e come da immagine allegata,
I titoli dei campi e la loro descrizione al di sotto non combaciano, così anche l'obbligatorietà.
Sarebbe corretto invertire i titoli?
Abbiamo notato che l'obbligatorietà potrebbe essere invertita anche sul tema per Wordpress.

### Includi link o screenshot

![image](https://user-images.githubusercontent.com/103657056/228783171-5cf6bceb-b1bd-4d32-b9bc-a029df5abe80.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @rdemichele , hai ragione, la descrizione (o il titolo) è invertito. Puoi proporre un fix tramite PR.

Riguardo l'obbligatorietà dei campi invece, questa è allineata al documento di architettura.
