### ISSUE TITLE
Inserimento allegati (come materiale informativo o moduli) nel contenuto Servizio

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#72]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Per molti servizi avremmo bisogno di inserire degli allegati informativi o di modulistica
Attualmente gli unici allegati associabili ad un servizio solo relazioni ai contenuti di tipo "Documenti pubblico", ma non crediamo vada bene per questi allegati perchè non hanno un "Numero di protocollo" che invece risulta essere un campo obbligatorio nel contenuto "Documenti pubblici" inoltre questo tipo di contenuto contiene anche altri campi che non sapremmo come compilare qualora dovessimo inserire qui questi allegati.

Come dobbiamo trattarli in questo caso? Possiamo creare uno o più nuovi campi di tipo allegato semplice?

### Includi link o screenshot

[Sezione demografici del Comune di Genova contenente i servizi e gli allegati sopra citati](https://smart.comune.genova.it/pages/residenza-0)

![immagine](https://user-images.githubusercontent.com/95076111/228799112-06d679aa-9f77-4742-a6bf-c19d8491fac8.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @smaraschin , il campo naturale per questi documenti dovrebbe essere "Documento pubblico".

Condivido la vostra richiesta, c'è un problema anche di allineamento rispetto all'architettura dell'informazione che non identifica il "numero di protocollo" come campo obbligatorio, mentre lo è da _back-office_.

In tal caso, posso suggerirvi di rimuovere il `required` da quel campo e utilizzare sin da subito la sezione Documenti della scheda servizio.

L'eventuale modifica del codice del tema Drupal può essere condivisa con tutti tramite PR.
