### ISSUE TITLE
Utilità campo "Promemoria accesso" nel contenuto Servizio

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#73]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel tipo di contenuto Servizio cosa deve contenere il campo testuale "Promemoria accesso"?

Abbiamo controllato sull'excel dell'[Architettura dell'Informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=335720294)
su figma e sui template statici ma non è presente.

Và rimuoverlo?

### Includi link o screenshot

![immagine](https://user-images.githubusercontent.com/95076111/228803754-12f3c154-30bd-44d9-b212-6871c9c22ddb.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @smaraschin , questo campo può essere tralasciato. Facciamo una verifica e lo rimuoviamo da _back-office_
