### ISSUE TITLE
Come inseriamo i Municipi?

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#74]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il Comune di Genova ha 9 Municipi, ognuno ha contenuti dedicati che riguardano la sua composizione, i contatti, le informazioni riguardo alle competenze, la lista delle sedute.

Quale tipo di contenuto dovrebbe accogliere un Municipio?
Dove è stato pensato di posizionare questa struttura di contenuti?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @smaraschin, nella nuova Architettura dell'informazione il content-type Unità Organizzativa mi sembra quella più vicina alla tua necessità. Cosa ne pensi?

**Comment by smaraschin** [comment]
Ciao @zetareticoli si lo pensavamo anche noi.
Cagliari effettivamente lo ha trattato [sia come ufficio](https://www.comune.cagliari.it/portale/page/it/municipalita_di_pirri?contentId=ORG9423) (quindi unità organizzativa)
che come [sotto argomento di Organi di governo](https://www.comune.cagliari.it/portale/it/amm_01_03.page?contentId=TGN15665) (tassonomia "Amministrazione")

Mentre nel sito del Comune di Bugliano lo hanno trattato solamente [come Luogo](https://www.comune.bugliano.pi.it/Vivere-il-comune/Luoghi/Palazzo-del-municipio) ma secondo me è poco efficiente così.

Ad ogni modo, se volessimo aggiungere un sottoargomento alla tassonomia ["Tipi di Unità Organizzativa" dell'Architettura dell'informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=1190038254) siamo liberi di farlo giusto? 
Perchè in questo caso sotto Struttura amministrativa si potrebbe aggiungere "Municipio"

**Comment by zetareticoli** [comment]
Sì, anche a livelli di alberatura mi viene da consigliare di posizionarli in Amministrazione / Aree amministrative

**Comment by zetareticoli** [comment]
@smaraschin se non ci sono altri dubbi, procedo con chiusura issue

**Comment by smaraschin** [comment]
Ok per questo punto direi che è risolto
grazie
