### ISSUE TITLE
Come comportarsi quando il canale fisico non è previsto dal servizio

### ISSUE THREAD

**Issue by MarinaRepetto** [italia/design-comuni-drupal-theme#76]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel tipo di contenuto Servizio, la compilazione del campo canale fisico è obbligatorio per il validatore.
Tuttavia in alcuni casi la compilazione di questo campo è fuorviante o non possibile. Esempi:

- **servizi che vengono erogati d'ufficio**: es. la consegna della tessera elettorale avviene d'ufficio e inviata a domicilio, il cittadino che compie diciottanni non deve richiederla nè può recarsi allo sportello. Dobbiamo fornire un contatto per poter chiedere eventuali informazioni ma è sbagliato indicare uno sportello fisico o dare la possibilità di prenotare un appuntamento.
- **servizi che possono essere fruiti solo online** es. "Sportello Unico per L'Edilizia" (le pratiche possono essere inviate dai professionisti solo per via telematica), "Cerca il tuo seggio", "Iscriviti al servizio di Allerta Meteo di Portezione Civile", "Consulta le mappe del Geoportale", "servizi PagoPA", ecc

Sapendo che è sempre buona norma laddove possibile dare un alternativa fisica all'utente, **vi chiediamo per favore di poter togliere l'obbligatorietà di questo campo**, che ci mette in difficoltà nella compilazione.
Piuttosto suggeriamo di aggiungere una nota per il redattore "indicare sempre il canale fisico laddove presente".

Grazie
Marina

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by gorobey** [comment]
Ciao @MarinaRepetto , hai perfettamente ragione,
e credo possa non essere l'unico caso in cui l'obbligatorietà di un campo impedisca la corretta pubblicazione di un contenuto.
Penso che l'intento originale fosse quello di obbligare il redatore a pubblicare ono o entrambi i campi.
Credo si possa risolvere utilizzando:
[conditional_fields](https://www.drupal.org/project/conditional_fields)

Faro qualche prova ti farò sapere.

**Comment by gorobey** [comment]
Ciao @MarinaRepetto , ho avuto modo di fare una prova,
a mio modesto parere potrebbe essere una buona soluzione,
ora bisognerebbe fare una lista di dove applicare lo stesso metodo per risolvere conflitti di obbligatorietà simili.
@astagi se quasta si può considerare come soluzione al problema si potrebbe aggiugere il modulo ai require in fase di installazione, inoltre sarebbero da aggiornare i file nella cartella "content" (come vengono generati? sono un export fatto da pannello?)

![Conditional Fields Manage Dependencies](https://user-images.githubusercontent.com/226759/233081711-6058ae27-f105-4a2e-8017-61169f11d097.png)

**Comment by zetareticoli** [comment]
Ciao @MarinaRepetto,

dopo aver valutato internamente la problematica, procederemo con la revisione dell'obbligatorietà del campo Accesso al canale fisico, rendendo le opzioni digitale e fisico come alternative.

La modifica al _back-office_ di Drupal non sarà immediata, aggiorneremo prima di tutto il documento di Architettura dell'Informazione. 

Nel mentre, ogni suggerimento come quelli di @gorobey sono ben accetti, siamo disponibili ad integrazioni nel tema base tramite PR.

Related to #78
