### ISSUE TITLE
Eventi nella sezione Vivere il Comune 

### ISSUE THREAD

**Issue by smaraschin** [italia/design-comuni-drupal-theme#77]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

La Sezione **Vivere il Comune**, è stata pensata per gli eventi istituzionali o per gli eventi nel comune? Quindi anche quelli turistici?
Nel nostro caso gli eventi del turismo vengono inseriti su un portale dedicato. Quali suggerimenti avete riguardo a questa situazione?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @smaraschin , la sezione è stata pensata per qualsiasi tipo di evento si svolga nel Comune, quindi sia istituzionali che turistici.

Vi suggerisco di integrare gli eventi pubblicati su un portale dedicato direttamente sul sito del Comune.
