### ISSUE TITLE
Problemi con la funzionalità "Prenota Appuntamento"

### ISSUE THREAD

**Issue by MarinaRepetto** [italia/design-comuni-drupal-theme#78]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel tipo di contenuto Servizio compare obbligatoriamente il bottone "prenota appuntamento".

- Vorremmo fare in modo che questo bottone compaia solo laddove sussista questa modalità di accesso al servizio (che non è presente nei servizi ad accesso diretto che sono presenti nel nostro Ente o nei servizi online vedi issue #76)
- Vorremmo inoltre che la funzionalità "Prenota Appuntamento" non obbligasse ad utilizzare lo strumento di gestione prenotazioni del sito, poichè noi disponiamo di altri strumenti evoluti di prenotazione (e come noi probabilmente altri Comuni). Il bottone potrebbe quindi, per esempio, essere collegato ad un campo di tipo url.

Avremmo bisogno di sapere se sussiste qualche impedimento a tali richieste.

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @MarinaRepetto,
ti ho risposto nella issue #76 per la prima parte.

Relativamente alla funzionalità di prenotazione appuntamento, questa è parte delle cosiddette funzionalità trasversali che sono anche oggetto di criterio di conformità. 

Eventuali strumenti "esterni" al sito del Comune devono essere integrati nell'esperienza unica di quest'ultimo.
