### ISSUE TITLE
Tipo di contenuto FAQ

### ISSUE THREAD

**Issue by MarinaRepetto** [italia/design-comuni-drupal-theme#79]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il tipo di contenuto FAQ è molto basico: consente solamente di scrivere domande e risposte che vanno a popolare una pagina generale di FAQ.
Per una migliore esperienza utente riteniamo sia necessario avere la possibilità di associare la FAQ alla categoria (anagrafe, tributi, mobilità ecc.) e all'argomento così come accade per il tipo di contenuto "servizio".

Vorremmo inoltre fare in modo che le FAQ possano essere riferite ad un Servizio qualora ve ne sia la necessità (es. nel sito attuale abbiamo avuto la necessità di pubblicare le FAQ relative al servizio "Ecoincentivi" per diminuire il carico di chiamate verso gli uffici di competenza).

Possiamo apportare queste modifiche al tipo di contenuto FAQ?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.1

**Comment by gorobey** [comment]
Ciao @MarinaRepetto , 
nel documento [Architettura dell'informazione Modello Comuni Designers Italia](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/) non si fa menzione alle domande frequenti, credo quindi possiamo considerarci liberi di proporre le modifiche, in questo caso a patto di condividerle in modo da mantenere l'uniformità dell'architettura tra i siti dei vari comuni.
