### ISSUE TITLE
Non vengono mostrati "Tempi e scadenze" nei servizi (proposta di correzione)

### ISSUE THREAD

**Issue by giannigiusti** [italia/design-comuni-drupal-theme#80]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Inserendo un servizio con campo "Tempi e scadenze (fasi semplici)", queste non vengono mostrate. Il problema si verifica per un errore di scrittura  nel tema node--servizio.html.twig per cui 

La linea  362 il codice (in particolare il campo field_fase_semplice[0] )
`        {% if content.field_tempi_e_scadenze[0] is not empty or field_fase_semplice[0] is not empty %}`

andrebbe corretto con:
`        {% if content.field_tempi_e_scadenze[0] is not empty  or content.field_fase_semplice[0] is not empty %}`
         

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

 1.7.0 ma il problema è anche nella 1.7.1

**Comment by zetareticoli** [comment]
Duplicate #81
