### ISSUE TITLE
Non viene mostrato "Tempi e scadenze" nell'INDICE della pagina dei servizi (proposta di correzione)

### ISSUE THREAD

**Issue by giannigiusti** [italia/design-comuni-drupal-theme#81]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Inserendo un nodo di tipo servizio con campo "tempi e scadenza (fase semplice)", non viene mostrata la voce nell'INDICE della pagina ("Tempi e scadenza").

Nel template "node--servizio.html.twig", la linea 269 che attualamente  riporta:
`{% if content.field_tempi_e_scadenze[0] is not empty %}`

Andrebbe cambiata con:
`{% if content.field_tempi_e_scadenze[0] is not empty  or content.field_fase_semplice[0] is not empty %}`

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.0 ma il problema è anche nella 1.7.1

**Comment by zetareticoli** [comment]
Ciao @giannigiusti , potresti suggerire la modifica come PR così provvediamo ad integrare nel tema base? Grazie
