### ISSUE TITLE
Incoerenza sul campo "Procedure collegate all'esito" - facoltativo o obbligatorio?

### ISSUE THREAD

**Issue by MarinaRepetto** [italia/design-comuni-drupal-theme#84]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel modello Drupal il campo "Procedure collegate all'esito" nel tipo di contenuto "Servizio" risulta essere un campo obbligatorio con asterisco.
Ci siamo però accorti che nel documento "Architettura dell'informazione Modello Comuni Designers Italia" https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=335720294 e nel layout Figma questo campo non risulta essere obbligatorio.

Abbiamo bisogno di sapere quale delle due indicazioni è corretta. Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
@MarinaRepetto Questo campo è opzionale, può essere modificato nel template
