### ISSUE TITLE
Aggiornamento a Drupal 10

### ISSUE THREAD

**Issue by savdev11** [italia/design-comuni-drupal-theme#92]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Proposta

Buongiorno,
entro fine anno il supporto a Drupal 9 terminerà. Questo modulo è ancora dipendente da Drupal 9. E' previsto un aggiornamento a Drupal 10 a breve?

Grazie

### Motivazione e contesto

Questa modifica è necessaria per evitare di avere problemi di sicurezza con le installazioni Drupal 9.

**Comment by astagi** [comment]
@savdev11 al momento purtroppo niente di ufficiale.
