### ISSUE TITLE
Nelle categorie delle novità, non visualizza le card specifiche

### ISSUE THREAD

**Issue by giannigiusti** [italia/design-comuni-drupal-theme#94]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-drupal-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-drupal-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Premendo su Novità e successivamente sulle singole categorie (Comunicati, Avvisi o Notizie), non vengono mostrate le card delle Novità della categoria specifica.
Esempio url:
https://metti_dominio_del_sito.quelchevuoi/tipi-di-notizia/avvisi

C'è da agire su quelche template specifico? suggerimenti su dove mettere mano? sarebbe poi la temizzazione di un term id (credo)

Il probema me lo da su due installazioni di prova aggiornate alle 1.8.0 (ma esisteva anche prima)

Grazie per l'attenzione
Gianni Giusti

### Includi link o screenshot

![Screenshot 2023-10-17 at 09-17-22 Avvisi Nome del comune](https://github.com/italia/design-comuni-drupal-theme/assets/125642301/dbe38234-1534-4550-a08b-d7d6ce4e121a)

Questo sopra è come viene.... e sotto, a mio avviso, come dovrebbe venire...

![Screenshot 2023-10-17 at 09-18-01 Avvisi Archivi - Comune di Vigata](https://github.com/italia/design-comuni-drupal-theme/assets/125642301/4a937ec8-c835-4284-b246-fde37051d885)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.8.0

**Comment by giannigiusti** [comment]
Avendo aggiornato dalla 1.7.1 alla 1.8, non so se la cosa è stata corretta nelle viste della 1.8.... comunque, guardando il problema, ho risolto modificando la views /admin/structure/views/view/argomenti_correlati/edit/block_1 relativa alle notizie.
La views in questione è sbagliata perchè prende come argomento la sola tassonomia relativa agli "argomenti", mentre dovrebbe prendere l'ID del termine di tassonomia a prescindere dal vocabolario. In parole povere, ho fatto le variazioni illustrate nell'immagine sotto.

Qualcuno mi conferma che è coretto in un installazione pulita della 1.8? 

![Argomenti Correlati](https://github.com/italia/design-comuni-drupal-theme/assets/125642301/2402e9b6-f143-4d21-a8f3-ab2207ce6108)

**Comment by astagi** [comment]
@rdemichele @smaraschin @gorobey potete aiutare @giannigiusti nel suo problema? grazie mille!

**Comment by rdemichele** [comment]
@astagi  @giannigiusti  Nella versione segnalata non è stato ancora creato un file ".twig" specifico per la tassonomia "Tipi di notizia" che infatti sta ereditando il twig utile alla tassonomia "Argomenti".
Suggerisco di creare il file "taxonomy-term--tipi-di-notizia.html.twig", al cui interno sarà possibile richiamare una vista specifica per la tassonomia "Tipi di notizia" passando come parametro il "term.id".

Si può prendere spunto dal codice di "taxonomy-term.html.twig", non bisognerà però richiamare la vista argomenti_correlati (perché è specifica per la tassonomia "Argomenti"); si potrà prendere spunto dalla vista "argomenti_correlati" per creare una nuova vista "tipi_di_notizia_collegati" (il nome è esemplificativo), bisognerà però configurare il parametro che si aspetta la vista che non sarà "Content: Argomenti" ma "Content: Tipo di notizia".

Nella vista che verrà creata si potranno configurare i filtri di ricerca, per farla somigliare allo screenshot che è stato allegato.

**Comment by giannigiusti** [comment]
Risolto grazie, 
ormai sono ad un ottimo punto dello sviluppo del sito comunale 

Grazie 


Il presente messaggio e-mail, e gli allegati allo stesso, sono indirizzati esclusivamente ai soggetti indicati come destinatari, sia che si tratti di destinatari diretti, sia che si tratti di destinatari a cui il messaggio è inviato per conoscenza. Solo i soggetti destinatari, autorizzati alla ricezione, possono effettuare il trattamento del presente messaggio e degli allegati nonché il trattamento dei dati in esso contenuti. Il contenuto del messaggio e degli allegati può avere natura confidenziale e/o privilegi legali. I dati personali contenuti nel messaggio e negli allegati devono essere trattati conformemente al Reg. n. 679/2016 UE (GDPR) del d.lgs. n. 196/2003, come modificato dal d.lgs.101/2018. E' pertanto illecito il trattamento da parte di soggetti non autorizzati ed è illecita, in particolare, la comunicazione e la diffusione dei dati personali in violazione delle disposizioni del GDPR e della normativa interna di adeguamento. Il soggetto non destinatario che, per errore, riceva il presente messaggio è tenuto a non leggere, non copiare, non inoltrare e non archiviare il messaggio medesimo. E' tenuto altresì a darne immediata comunicazione al mittente, anche inviando un messaggio di ritorno all'indirizzo e-mail del mittente medesimo, nonché a eliminare integralmente il messaggio dal proprio sistema informatico, server e client. 


Da: "rdemichele" ***@***.***> 
A: "italia/design-comuni-drupal-theme" ***@***.***> 
Cc: "giannigiusti" ***@***.***>, "Mention" ***@***.***> 
Inviato: Lunedì, 8 gennaio 2024 17:26:54 
Oggetto: Re: [italia/design-comuni-drupal-theme] Nelle categorie delle novità, non visualizza le card specifiche (Issue #94) 





[ https://github.com/astagi | @astagi ] [ https://github.com/giannigiusti | @giannigiusti ] Nella versione segnalata non è stato ancora creato un file ".twig" specifico per la tassonomia "Tipi di notizia" che infatti sta ereditando il twig utile alla tassonomia "Argomenti". 
Suggerisco di creare il file "taxonomy-term--tipi-di-notizia.html.twig", al cui interno sarà possibile richiamare una vista specifica per la tassonomia "Tipi di notizia" passando come parametro il "term.id". 

Si può prendere spunto dal codice di "taxonomy-term.html.twig", non bisognerà però richiamare la vista argomenti_correlati (perché è specifica per la tassonomia "Argomenti"); si potrà prendere spunto dalla vista "argomenti_correlati" per creare una nuova vista "tipi_di_notizia_collegati" (il nome è esemplificativo), bisognerà però configurare il parametro che si aspetta la vista che non sarà "Content: Argomenti" ma "Content: Tipo di notizia". 

Nella vista che verrà creata si potranno configurare i filtri di ricerca, per farla somigliare allo screenshot che è stato allegato.
